### ISSUE TITLE
More than one sensu server

### ISSUE THREAD

**Issue by adambarnett52** [mrichar1/dashing-sensu#5]
Hi

I have been trying get this working with more than one sensu server
We have 4
Is there a way to that?

**Comment by mrichar1** [comment]
Apologies for taking so long to answer this one!

The sensu API doesn't seem to have a way to aggregate results from multiple sensu servers into one place. Uchiwa has a concept of dashboards, so we could potentially do something similar to this...

I imagine it would be possible to put a list of servers and their credentials, rather than a single set, and then loop over each server in turn, pulling in it's events, and collating them all into one widget. I could try and implement this, but with only one server it might be hard to test.

A short-term hack alternative would be to make multiple copies of the sensu.rb job file with different credentials and connect different widgets in the dashboard to the different jobs. 

Let me know if fixing this 'properly' is still of interest to you, or if you've found a suitable workaround...
